<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <joint name="camera_joint" type="fixed">
        <parent link="chassis" />
        <child link="camera_link" />
        <origin xyz="${3/4 * length} 0 ${height + 0.5}" rpy="0 0 0" />
    </joint>

    <link name="camera_link">
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="camera_link_optical" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>

        <sensor name="camera" type="depth">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <camera>
                <horizontal_fov>1.85</horizontal_fov>
                <image>
                    <format>B8G8R8</format>
                    <width>320</width>
                    <height>100</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>

            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
                <min_depth>0.001</min_depth>
                <max_depth>100.0</max_depth>
            </plugin>
            
        </sensor>
    </gazebo> 

</robot>