<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <joint name="laser_3d_joint" type="fixed">
        <parent link="chassis" />
        <child link="laser_3d_frame" />
        <origin xyz="${3/4 * length} 0 ${height + 0.5}" rpy="0 0 0" />
    </joint>

    <link name="laser_3d_frame">
    </link>

    <gazebo reference="laser_3d_frame">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>100</samples>
                        <resolution>1.0</resolution>
                        <min_angle>-1.22</min_angle>
                        <max_angle>1.22</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>70</samples>
                        <resolution>1.0</resolution>
                        <min_angle>-0.3</min_angle>
                        <max_angle>0.785</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>5</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="laser_scanner" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <namespace>/</namespace>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/PointCloud2</output_type>
                <frame_name>laser_3d_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>
