<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="robot_material.xacro" />
    <xacro:include filename="inertial_macros.xacro" />

    <xacro:property name="width" value="0.3" />
    <xacro:property name="length" value="0.3" />
    <xacro:property name="height" value="0.15" />
    <xacro:property name="wheeldiam" value="0.1" />
    <xacro:property name="wheellen" value="0.04" />

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- CHASSIS LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -${wheeldiam/2}" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-length/3} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${length/2} 0 ${height/2}" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="${length/2} 0 ${height/2}" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="${length}" y="${width}" z="${height}">
            <origin xyz="${length/2} 0 ${height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel"/>
        <origin xyz="0 ${width/2 + wheellen/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheeldiam/2}" length="${wheellen}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheeldiam/2}" length="${wheellen}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.1" radius="${wheeldiam/2}" length="${wheellen}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel"/>
        <origin xyz="0 -${width/2 + wheellen/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheeldiam/2}" length="${wheellen}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheeldiam/2}" length="${wheellen}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.1" radius="${wheeldiam/2}" length="${wheellen}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEK LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${3/4 * length} 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheeldiam/2}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheeldiam/2}"/>
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="0.1" radius="${wheeldiam/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
